from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/freshgo', methods=['GET'])
def get_users():
    return jsonify([
        {
            "id": 1,
            "amount": 1,
            "name": "Organic Avocado",
            "category": "fruits",
            "img": "img/avocado.jpg",
            "price": 270,
            "type": "veg",
        },
        {
            "id": 2,
            "amount": 1,
            "name": "Fresh Pineapple",
            "category": "fruits",
            "img": "img/pineapple.jpg",
            "price": 90,
            "type": "veg",
        },
        {
            "id": 3,
            "amount": 1,
            "name": "Best Pomegranate",
            "category": "fruits",
            "img": "img/dalimb.jpg",
            "price": 160,
            "type": "veg",
        },
        {
            "id": 4,
            "amount": 1,
            "name": "Fresh Tomato",
            "category": "fruits",
            "img": "img/tomato.jpg",
            "price": 55,
            "type": "veg",
        },
        {
            "id": 5,
            "amount": 1,
            "name": "Capsicum",
            "category": "vegetables",
            "img": "img/capsicum.jpg",
            "price": 140,
            "type": "veg",
        },
        {
            "id": 6,
            "amount": 1,
            "name": "Coriander",
            "category": "vegetables",
            "img": "img/coriander.jpg",
            "price": 20,
            "type": "veg",
        },
        {
            "id": 7,
            "amount": 1,
            "name": "Brinjal",
            "category": "vegetables",
            "img": "img/brinjal.jpg",
            "price": 60,
            "type": "veg",
        },
        {
            "id": 8,
            "amount": 1,
            "name": "Radish",
            "category": "vegetables",
            "img": "img/radish.jpg",
            "price": 70,
            "type": "veg",
        },
        {
            "id": 9,
            "amount": 1,
            "name": "Walnut",
            "category": "dryfruits",
            "img": "img/walnuts.jpg",
            "price": 799,
            "type": "veg",
            "type2": "organic",
        },
        {
            "id": 10,
            "amount": 1,
            "name": "Milk",
            "category": "Healthy",
            "img": "img/milk.jpg",
            "price": 60,
            "type": "veg",
            "type2": "organic",
        },
        {
            "id": 11,
            "amount": 1,
            "name": "Eggs",
            "category": "Healthy",
            "img": "img/eggs.jpg",
            "price": 130,
            "type": "nonveg",
            "type2": "organic",
        },
        {
            "id": 12,
            "amount": 1,
            "name": "Tofu",
            "category": "Healthy",
            "img": "img/tofu.jpg",
            "price": 200,
            "type": "veg",
            "type2": "organic",
        },
        {
            "id": 13,
            "amount": 1,
            "name": "Chicken",
            "category": "Protein",
            "img": "img/chicken.jpg",
            "price": 220,
            "type": "nonveg",
            "type2": "others",
        },
        {
            "id": 14,
            "amount": 1,
            "name": "Salmon Fish",
            "category": "Rich Nutrients",
            "img": "img/salmonfish.jpg",
            "price": 500,
            "type": "nonveg",
            "type2": "others",
        },
        {
            "id": 15,
            "amount": 1,
            "name": "Goat Meat",
            "category": "Healthy",
            "img": "img/goat.jpg",
            "price": 800,
            "type": "nonveg",
            "type2": "others",
        },
    ])

@app.route('/freshgo', methods=['DELETE'])
def delete_user():
    return jsonify({'result': 'success'})

if __name__ == '__main__':
    app.run(debug=True)
